//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VendingMachine.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VendingMachine.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AddCoin.
        /// </summary>
        internal static string AddCoin {
            get {
                return ResourceManager.GetString("AddCoin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BuyProduct.
        /// </summary>
        internal static string BuyProduct {
            get {
                return ResourceManager.GetString("BuyProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change.
        /// </summary>
        internal static string Change {
            get {
                return ResourceManager.GetString("Change", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CoinCount.
        /// </summary>
        internal static string CoinCount {
            get {
                return ResourceManager.GetString("CoinCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CoinName.
        /// </summary>
        internal static string CoinName {
            get {
                return ResourceManager.GetString("CoinName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DropCoin.
        /// </summary>
        internal static string DropCoin {
            get {
                return ResourceManager.GetString("DropCoin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GoodsTitle.
        /// </summary>
        internal static string GoodsTitle {
            get {
                return ResourceManager.GetString("GoodsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to InfoBarMessageControlErrorTitle.
        /// </summary>
        internal static string InfoBarMessageControlErrorTitle {
            get {
                return ResourceManager.GetString("InfoBarMessageControlErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NotEnoughMoneyMessage.
        /// </summary>
        internal static string NotEnoughMoneyMessage {
            get {
                return ResourceManager.GetString("NotEnoughMoneyMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PleaseWait.
        /// </summary>
        internal static string PleaseWait {
            get {
                return ResourceManager.GetString("PleaseWait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ProductCount.
        /// </summary>
        internal static string ProductCount {
            get {
                return ResourceManager.GetString("ProductCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ProductName.
        /// </summary>
        internal static string ProductName {
            get {
                return ResourceManager.GetString("ProductName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ProductPrice.
        /// </summary>
        internal static string ProductPrice {
            get {
                return ResourceManager.GetString("ProductPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SuccessMessage.
        /// </summary>
        internal static string SuccessMessage {
            get {
                return ResourceManager.GetString("SuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SystemWalletTitle.
        /// </summary>
        internal static string SystemWalletTitle {
            get {
                return ResourceManager.GetString("SystemWalletTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UserBalance.
        /// </summary>
        internal static string UserBalance {
            get {
                return ResourceManager.GetString("UserBalance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UserWalletTitle.
        /// </summary>
        internal static string UserWalletTitle {
            get {
                return ResourceManager.GetString("UserWalletTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WarningTitle.
        /// </summary>
        internal static string WarningTitle {
            get {
                return ResourceManager.GetString("WarningTitle", resourceCulture);
            }
        }
    }
}
